from pathlib import Path

import numpy as np
import pandas as pd


BACKTEST_FILE = Path("data/processed/backtest_returns.csv")
REPORT_FILE = Path("data/processed/performance_metrics.csv")


def load_backtest():
    """
    Load the daily portfolio returns generated by the backtest.
    """

    if not BACKTEST_FILE.exists():
        raise FileNotFoundError(
            f"Backtest file not found: {BACKTEST_FILE}"
        )

    df = pd.read_csv(BACKTEST_FILE)

    df["Date"] = pd.to_datetime(df["Date"])

    df = df.sort_values("Date").reset_index(drop=True)

    if "portfolio_return" not in df.columns:
        raise ValueError(
            "Column 'portfolio_return' is missing from backtest data."
        )

    df["portfolio_return"] = pd.to_numeric(
        df["portfolio_return"],
        errors="coerce"
    )

    if df["portfolio_return"].isna().any():
        raise ValueError(
            "Backtest contains missing portfolio returns."
        )

    return df


def calculate_metrics(df):
    """
    Calculate standard portfolio performance statistics.
    """

    returns = df["portfolio_return"]

    # ---------------------------------------------------------
    # Basic statistics
    # ---------------------------------------------------------

    trading_days = len(returns)

    mean_daily_return = returns.mean()

    daily_volatility = returns.std(ddof=1)

    # ---------------------------------------------------------
    # Annualized return
    # ---------------------------------------------------------

    cumulative_wealth = (1 + returns).cumprod()

    final_wealth = cumulative_wealth.iloc[-1]

    years = trading_days / 252

    annualized_return = final_wealth ** (1 / years) - 1

    # ---------------------------------------------------------
    # Annualized volatility
    # ---------------------------------------------------------

    annualized_volatility = daily_volatility * np.sqrt(252)

    # ---------------------------------------------------------
    # Sharpe ratio
    #
    # Assumes zero risk-free rate for now.
    # ---------------------------------------------------------

    if daily_volatility > 0:
        sharpe_ratio = (
            mean_daily_return / daily_volatility
        ) * np.sqrt(252)
    else:
        sharpe_ratio = np.nan

    # ---------------------------------------------------------
    # Downside deviation
    # ---------------------------------------------------------

    negative_returns = returns[returns < 0]

    if len(negative_returns) > 0:
        downside_deviation = (
            np.sqrt(
                np.mean(
                    negative_returns ** 2
                )
            )
            * np.sqrt(252)
        )
    else:
        downside_deviation = np.nan

    # ---------------------------------------------------------
    # Sortino ratio
    # ---------------------------------------------------------

    if downside_deviation > 0:
        sortino_ratio = (
            annualized_return / downside_deviation
        )
    else:
        sortino_ratio = np.nan

    # ---------------------------------------------------------
    # Maximum drawdown
    # ---------------------------------------------------------

    running_max = cumulative_wealth.cummax()

    drawdown = (
        cumulative_wealth / running_max
    ) - 1

    maximum_drawdown = drawdown.min()

    # ---------------------------------------------------------
    # Calmar ratio
    # ---------------------------------------------------------

    if maximum_drawdown < 0:
        calmar_ratio = (
            annualized_return / abs(maximum_drawdown)
        )
    else:
        calmar_ratio = np.nan

    # ---------------------------------------------------------
    # Win rate
    # ---------------------------------------------------------

    win_rate = (returns > 0).mean()

    # ---------------------------------------------------------
    # Best / worst days
    # ---------------------------------------------------------

    best_day = returns.max()

    worst_day = returns.min()

    # ---------------------------------------------------------
    # Average gain / loss
    # ---------------------------------------------------------

    winning_returns = returns[returns > 0]
    losing_returns = returns[returns < 0]

    average_gain = (
        winning_returns.mean()
        if len(winning_returns) > 0
        else np.nan
    )

    average_loss = (
        losing_returns.mean()
        if len(losing_returns) > 0
        else np.nan
    )

    # ---------------------------------------------------------
    # Profit factor
    # ---------------------------------------------------------

    gross_profit = winning_returns.sum()

    gross_loss = abs(losing_returns.sum())

    if gross_loss > 0:
        profit_factor = gross_profit / gross_loss
    else:
        profit_factor = np.nan

    # ---------------------------------------------------------
    # Metrics dictionary
    # ---------------------------------------------------------

    metrics = {
        "trading_days": trading_days,
        "start_date": df["Date"].min().date(),
        "end_date": df["Date"].max().date(),
        "final_wealth": final_wealth,
        "cumulative_return": final_wealth - 1,
        "mean_daily_return": mean_daily_return,
        "daily_volatility": daily_volatility,
        "annualized_return": annualized_return,
        "annualized_volatility": annualized_volatility,
        "sharpe_ratio": sharpe_ratio,
        "sortino_ratio": sortino_ratio,
        "maximum_drawdown": maximum_drawdown,
        "calmar_ratio": calmar_ratio,
        "win_rate": win_rate,
        "best_day": best_day,
        "worst_day": worst_day,
        "average_gain": average_gain,
        "average_loss": average_loss,
        "profit_factor": profit_factor,
    }

    return metrics


def save_metrics(metrics):
    """
    Save performance metrics to CSV.
    """

    REPORT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    report = pd.DataFrame(
        [metrics]
    )

    report.to_csv(
        REPORT_FILE,
        index=False
    )

    return report


def print_metrics(metrics):
    """
    Print performance statistics in a readable format.
    """

    print()
    print("Portfolio Performance")
    print("=====================")

    print(
        f"Trading days:          {metrics['trading_days']}"
    )

    print(
        f"Date range:            "
        f"{metrics['start_date']} to "
        f"{metrics['end_date']}"
    )

    print(
        f"Final wealth:          "
        f"{metrics['final_wealth']:.4f}"
    )

    print(
        f"Cumulative return:     "
        f"{metrics['cumulative_return']:.2%}"
    )

    print(
        f"Annualized return:     "
        f"{metrics['annualized_return']:.2%}"
    )

    print(
        f"Annualized volatility: "
        f"{metrics['annualized_volatility']:.2%}"
    )

    print(
        f"Sharpe ratio:          "
        f"{metrics['sharpe_ratio']:.4f}"
    )

    print(
        f"Sortino ratio:         "
        f"{metrics['sortino_ratio']:.4f}"
    )

    print(
        f"Maximum drawdown:      "
        f"{metrics['maximum_drawdown']:.2%}"
    )

    print(
        f"Calmar ratio:          "
        f"{metrics['calmar_ratio']:.4f}"
    )

    print(
        f"Win rate:              "
        f"{metrics['win_rate']:.2%}"
    )

    print(
        f"Best day:              "
        f"{metrics['best_day']:.2%}"
    )

    print(
        f"Worst day:             "
        f"{metrics['worst_day']:.2%}"
    )

    print(
        f"Average gain:          "
        f"{metrics['average_gain']:.2%}"
    )

    print(
        f"Average loss:          "
        f"{metrics['average_loss']:.2%}"
    )

    print(
        f"Profit factor:         "
        f"{metrics['profit_factor']:.4f}"
    )

    print()
    print(
        f"Saved to: {REPORT_FILE}"
    )


def run_performance_analysis():
    """
    Complete performance analysis pipeline.
    """

    df = load_backtest()

    metrics = calculate_metrics(df)

    save_metrics(metrics)

    print_metrics(metrics)

    return metrics


if __name__ == "__main__":
    run_performance_analysis()